# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Roast Me!' do
use_frameworks!
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'XHAmazingLoading'
pod 'Firebase', '>= 2.3.3'
pod 'ICETutorial', '~> 1.1.1'
pod 'MFSideMenu'
pod 'JGProgressHUD'
pod 'Fabric'
pod 'GPUImage', '~> 0.1'
#pod "AFViewShaker", "~> 0.0.2"
#pod 'KNMultiItemSelector', '~> 1.0'
link_with 'Roast Me!', 'Roast Me! Dev' 'Roast Me! Tests'
end

target 'Roast Me!Tests' do

end

